### ISSUE TITLE
terminal doesn't launch

### ISSUE THREAD

**Issue by thob** [jetbug123/ulauncher-ssh#4]
I have everything setup in .ssh. I'm actually using the config setting for the CLI. What is needed to initiate it in Ulauncher. I'm on Linux Mint 19 and using Terminator

**Comment by jetbug123** [comment]
Have you specified terminator as your terminal in the plugins preferences?
By default xterm will be used.

**Comment by thob** [comment]
I did

**Comment by jetbug123** [comment]
Apparently it is an issue with terminator and how the plugin launches it.
But sadly I don't know how to fix it, nor have I much time to look into it further.
If someone else knows how to fix it, I will gladly accept a pull request :)

`Traceback (most recent call last):
  File "/usr/bin/terminator", line 23, in <module>
    import psutil
  File "/usr/lib/python3.7/site-packages/psutil/__init__.py", line 95, in <module>
    from . import _pslinux as _psplatform
  File "/usr/lib/python3.7/site-packages/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name _psutil_linux`

**Comment by thob** [comment]
For the sake of completness. It doesn't work with the Gnome Terminal either. works w/ xterm.

**Comment by petrarca-arezzo** [comment]
I seem to have a similar issue - the terminal is not opening. I'm on the latest stable Manjaro with KDE Plasma. The command `konsole --new-tab -e ssh nas` works perfectly fine from the command-line and ulauncher is offering the correct list of my ssh hosts.
My extension config is:
![Screenshot](https://user-images.githubusercontent.com/74855438/145438151-0fc0e777-3484-4d52-be12-4635b88e5ac1.png)

**Comment by petrarca-arezzo** [comment]
I made a small change to the script - I changed the `launch_terminal` function slightly to split the whole command:
```
        cmd = self.terminal + " " + self.terminal_arg + " " + self.terminal_cmd.replace("%SHELL",  shell).replace("%CONN", addr)
        if self.terminal:
            subprocess.Popen(shlex.split(cmd))
```
And now it's working for me at least. I can even remove the quotes around the Terminal cmd in the preferences. Maybe check yourself if the above makes sense (this is the first time I worked with Typescript).
